version: '3'

services:
  event-applications:
    container_name: event-applications
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: db
    restart: on-failure
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=eventApplication
      - MYSQL_USER=Developer
      - MYSQL_PASSWORD=secretPassword123
      - MYSQL_ROOT_PASSWORD=rootPassword321
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

volumes:
  db_data:
