version: '3'

services:
  event-applications:
    container_name: event-applications
    restart: on-failure
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
